# Site settings
title: Richard M. Smith
email: richsmith15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the homepage for Richard M. Smith.  Updates to follow soon.
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: smudgerville
github_username:  smudgerville

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
